
package vista;

public class VExpReg extends javax.swing.JFrame {

    /**
     * Creates new form Automata
     */
    public VExpReg() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPnMainPanel = new javax.swing.JPanel();
        jTbBorrar = new javax.swing.JToggleButton();
        jPnAutomata = new javax.swing.JPanel();
        jCbEmail = new javax.swing.JCheckBox();
        jCbBinario = new javax.swing.JCheckBox();
        jCbNotCient = new javax.swing.JCheckBox();
        jCbEntero = new javax.swing.JCheckBox();
        jCbReal = new javax.swing.JCheckBox();
        txReal = new javax.swing.JTextField();
        txEntero = new javax.swing.JTextField();
        txNotCient = new javax.swing.JTextField();
        txBinario = new javax.swing.JTextField();
        txEmail = new javax.swing.JTextField();
        jEmail = new javax.swing.JLabel();
        jBinario = new javax.swing.JLabel();
        jNotCient = new javax.swing.JLabel();
        jEntero = new javax.swing.JLabel();
        jReal = new javax.swing.JLabel();
        jPnDecorativo1 = new javax.swing.JPanel();
        jTitulo = new javax.swing.JLabel();
        jPnDecorativo2 = new javax.swing.JPanel();
        jPnBotonesValidacion = new javax.swing.JPanel();
        jbValidarBinario = new javax.swing.JButton();
        jbValidarNotCient = new javax.swing.JButton();
        jbValidarEntero = new javax.swing.JButton();
        jbValidarReal = new javax.swing.JButton();
        jbValidarEmail = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setForeground(new java.awt.Color(255, 51, 102));

        jPnMainPanel.setBackground(new java.awt.Color(236, 233, 61));
        jPnMainPanel.setForeground(new java.awt.Color(236, 233, 61));
        jPnMainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTbBorrar.setBackground(new java.awt.Color(204, 255, 204));
        jTbBorrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/trash icon_edited.png"))); // NOI18N
        jPnMainPanel.add(jTbBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 90, 120, 130));

        jPnAutomata.setBackground(new java.awt.Color(0, 0, 0));

        jCbEmail.setBackground(new java.awt.Color(255, 255, 102));
        jCbEmail.setForeground(new java.awt.Color(255, 255, 153));

        jCbBinario.setBackground(new java.awt.Color(255, 255, 102));
        jCbBinario.setForeground(new java.awt.Color(255, 255, 153));

        jCbNotCient.setBackground(new java.awt.Color(255, 255, 102));
        jCbNotCient.setForeground(new java.awt.Color(255, 255, 153));

        jCbEntero.setBackground(new java.awt.Color(255, 255, 102));
        jCbEntero.setForeground(new java.awt.Color(255, 255, 153));

        jCbReal.setBackground(new java.awt.Color(255, 255, 102));
        jCbReal.setForeground(new java.awt.Color(255, 255, 153));

        jEmail.setForeground(new java.awt.Color(255, 204, 204));
        jEmail.setText("Correo electrónico:");

        jBinario.setForeground(new java.awt.Color(255, 204, 204));
        jBinario.setText("Binario:");

        jNotCient.setForeground(new java.awt.Color(255, 204, 204));
        jNotCient.setText("Notación científica:");

        jEntero.setForeground(new java.awt.Color(255, 204, 204));
        jEntero.setText("Entero:");

        jReal.setForeground(new java.awt.Color(255, 204, 204));
        jReal.setText("Real:");

        javax.swing.GroupLayout jPnAutomataLayout = new javax.swing.GroupLayout(jPnAutomata);
        jPnAutomata.setLayout(jPnAutomataLayout);
        jPnAutomataLayout.setHorizontalGroup(
            jPnAutomataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnAutomataLayout.createSequentialGroup()
                .addGroup(jPnAutomataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPnAutomataLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPnAutomataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jReal)
                            .addComponent(jEntero)
                            .addComponent(jNotCient)
                            .addComponent(jEmail)))
                    .addGroup(jPnAutomataLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jBinario)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addGroup(jPnAutomataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPnAutomataLayout.createSequentialGroup()
                        .addComponent(txReal, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jCbReal))
                    .addGroup(jPnAutomataLayout.createSequentialGroup()
                        .addComponent(txEntero, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jCbEntero))
                    .addGroup(jPnAutomataLayout.createSequentialGroup()
                        .addComponent(txNotCient, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jCbNotCient))
                    .addGroup(jPnAutomataLayout.createSequentialGroup()
                        .addComponent(txBinario, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jCbBinario))
                    .addGroup(jPnAutomataLayout.createSequentialGroup()
                        .addComponent(txEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jCbEmail)))
                .addGap(14, 14, 14))
        );
        jPnAutomataLayout.setVerticalGroup(
            jPnAutomataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnAutomataLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPnAutomataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPnAutomataLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jReal))
                    .addGroup(jPnAutomataLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(txReal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jCbReal))
                .addGap(4, 4, 4)
                .addGroup(jPnAutomataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPnAutomataLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jEntero))
                    .addGroup(jPnAutomataLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(txEntero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jCbEntero))
                .addGap(4, 4, 4)
                .addGroup(jPnAutomataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPnAutomataLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jNotCient))
                    .addGroup(jPnAutomataLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(txNotCient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jCbNotCient))
                .addGroup(jPnAutomataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPnAutomataLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(jPnAutomataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPnAutomataLayout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(txBinario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jCbBinario))
                        .addGap(4, 4, 4))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPnAutomataLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBinario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPnAutomataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPnAutomataLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jEmail))
                    .addComponent(txEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCbEmail))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPnMainPanel.add(jPnAutomata, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 440, -1));

        jPnDecorativo1.setBackground(new java.awt.Color(51, 0, 255));
        jPnDecorativo1.setForeground(new java.awt.Color(51, 0, 255));

        jTitulo.setFont(new java.awt.Font("Sylfaen", 0, 36)); // NOI18N
        jTitulo.setForeground(new java.awt.Color(255, 204, 51));
        jTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTitulo.setText("AFN's ");

        javax.swing.GroupLayout jPnDecorativo1Layout = new javax.swing.GroupLayout(jPnDecorativo1);
        jPnDecorativo1.setLayout(jPnDecorativo1Layout);
        jPnDecorativo1Layout.setHorizontalGroup(
            jPnDecorativo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnDecorativo1Layout.createSequentialGroup()
                .addGap(277, 277, 277)
                .addComponent(jTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(214, Short.MAX_VALUE))
        );
        jPnDecorativo1Layout.setVerticalGroup(
            jPnDecorativo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPnDecorativo1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPnMainPanel.add(jPnDecorativo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 51));

        jPnDecorativo2.setBackground(new java.awt.Color(255, 204, 204));
        jPnDecorativo2.setPreferredSize(new java.awt.Dimension(49, 738));
        jPnDecorativo2.setRequestFocusEnabled(false);

        javax.swing.GroupLayout jPnDecorativo2Layout = new javax.swing.GroupLayout(jPnDecorativo2);
        jPnDecorativo2.setLayout(jPnDecorativo2Layout);
        jPnDecorativo2Layout.setHorizontalGroup(
            jPnDecorativo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 51, Short.MAX_VALUE)
        );
        jPnDecorativo2Layout.setVerticalGroup(
            jPnDecorativo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPnMainPanel.add(jPnDecorativo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 0, 51, 330));

        jPnBotonesValidacion.setBackground(new java.awt.Color(255, 153, 51));
        jPnBotonesValidacion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jbValidarBinario.setBackground(new java.awt.Color(0, 102, 102));
        jbValidarBinario.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jbValidarBinario.setForeground(new java.awt.Color(153, 255, 153));
        jbValidarBinario.setText("BINARIO");
        jbValidarBinario.setMaximumSize(new java.awt.Dimension(88, 49));
        jbValidarBinario.setMinimumSize(new java.awt.Dimension(88, 49));

        jbValidarNotCient.setBackground(new java.awt.Color(0, 102, 102));
        jbValidarNotCient.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jbValidarNotCient.setForeground(new java.awt.Color(153, 255, 153));
        jbValidarNotCient.setText("NOT. CIENTÍFICA");
        jbValidarNotCient.setMaximumSize(new java.awt.Dimension(88, 49));
        jbValidarNotCient.setMinimumSize(new java.awt.Dimension(88, 49));

        jbValidarEntero.setBackground(new java.awt.Color(0, 102, 102));
        jbValidarEntero.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jbValidarEntero.setForeground(new java.awt.Color(153, 255, 153));
        jbValidarEntero.setText("ENTERO");
        jbValidarEntero.setMaximumSize(new java.awt.Dimension(88, 49));
        jbValidarEntero.setMinimumSize(new java.awt.Dimension(88, 49));

        jbValidarReal.setBackground(new java.awt.Color(0, 102, 102));
        jbValidarReal.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jbValidarReal.setForeground(new java.awt.Color(153, 255, 153));
        jbValidarReal.setText("REAL");
        jbValidarReal.setMaximumSize(new java.awt.Dimension(88, 49));
        jbValidarReal.setMinimumSize(new java.awt.Dimension(88, 49));

        jbValidarEmail.setBackground(new java.awt.Color(0, 102, 102));
        jbValidarEmail.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jbValidarEmail.setForeground(new java.awt.Color(153, 255, 153));
        jbValidarEmail.setText("EMAIL");
        jbValidarEmail.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbValidarEmail.setMaximumSize(new java.awt.Dimension(88, 49));
        jbValidarEmail.setMinimumSize(new java.awt.Dimension(88, 49));

        javax.swing.GroupLayout jPnBotonesValidacionLayout = new javax.swing.GroupLayout(jPnBotonesValidacion);
        jPnBotonesValidacion.setLayout(jPnBotonesValidacionLayout);
        jPnBotonesValidacionLayout.setHorizontalGroup(
            jPnBotonesValidacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnBotonesValidacionLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jbValidarReal, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbValidarEntero, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbValidarNotCient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbValidarBinario, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbValidarEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPnBotonesValidacionLayout.setVerticalGroup(
            jPnBotonesValidacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnBotonesValidacionLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPnBotonesValidacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbValidarReal, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbValidarEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbValidarEntero, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbValidarNotCient, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbValidarBinario, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        jPnMainPanel.add(jPnBotonesValidacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 460, 70));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPnMainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPnMainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VExpReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VExpReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VExpReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VExpReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new VExpReg().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jBinario;
    public javax.swing.JCheckBox jCbBinario;
    public javax.swing.JCheckBox jCbEmail;
    public javax.swing.JCheckBox jCbEntero;
    public javax.swing.JCheckBox jCbNotCient;
    public javax.swing.JCheckBox jCbReal;
    private javax.swing.JLabel jEmail;
    private javax.swing.JLabel jEntero;
    private javax.swing.JLabel jNotCient;
    private javax.swing.JPanel jPnAutomata;
    private javax.swing.JPanel jPnBotonesValidacion;
    private javax.swing.JPanel jPnDecorativo1;
    private javax.swing.JPanel jPnDecorativo2;
    public javax.swing.JPanel jPnMainPanel;
    private javax.swing.JLabel jReal;
    public javax.swing.JToggleButton jTbBorrar;
    private javax.swing.JLabel jTitulo;
    public javax.swing.JButton jbValidarBinario;
    public javax.swing.JButton jbValidarEmail;
    public javax.swing.JButton jbValidarEntero;
    public javax.swing.JButton jbValidarNotCient;
    public javax.swing.JButton jbValidarReal;
    public javax.swing.JTextField txBinario;
    public javax.swing.JTextField txEmail;
    public javax.swing.JTextField txEntero;
    public javax.swing.JTextField txNotCient;
    public javax.swing.JTextField txReal;
    // End of variables declaration//GEN-END:variables
}
